#!/bin/sh -ex

cd "$(dirname "$0")"

unset -v feed_remake index_remake HTML

for txt in ./text/*; do
	html="./blog/${txt##*/}.html"
	if [ ! -f "$html" ] || [ "$(find "$txt" -newer "$html")" ]; then
		./genhtml "$txt" > "$html"
		./genplain < "$txt" > ./phlog/"${txt##*/}"
		feed_remake=1
	fi
done

idx=./blog/index.html
if [ ! -f "$idx" ] || [ "$(find . -type f -newer "$idx")" ]; then
	index_remake=1
fi

if [ "$index_remake" ]; then
	find ./text/ -type f ! -path '*/.*' | sort -r | ./genindex > ./blog/index.html
fi

if [ "$feed_remake" ] || [ ! -f ./blog/feed.xml ] || [ ! -f ./phlog/feed.xml ]; then
	HTML=1 ./genfeed > ./blog/feed.xml
	./genfeed > ./phlog/feed.xml
fi

