#!/bin/sh -ex

cd "$(dirname "$0")"

. ./blog.info/info
export LINK TITLE AUTHOR DESCRIPTION

cd text
unset -v feed_remake index_remake

for txt in *; do
	html="../blog/$txt.html"
	if [ ! -f "$html" ] || [ "$(find "$txt" -newer "$html")" ]; then
		../genhtml "$txt" > "$html"
		feed_remake=1
	fi
done

if [ ! -f index.html ] || [ "$(find . -type f -newer index.html)" ]; then
	index_remake=1
fi

if [ "$index_remake" ]; then
	find . -type f | sort -r | ../genindex > ../blog/index.html
fi

if [ "$feed_remake" ] || [ ! -f feed.xml ]; then
	../genfeed > ../blog/feed.xml
fi

