#!/bin/sh -ex

# works like make's target: prerequisite
outofdate() { [ ! -f "$1" ] || [ "$(find "$2" -type f -newer "$1")" ]; }

cd "$(dirname "$0")"

for txt in ./text/*; do
	if outofdate ./blog/"${txt##*/}".html "$txt"; then
		./genhtml "$txt" > ./blog/"${txt##*/}".html
	fi

	if outofdate ./phlog/"${txt##*/}".txt "$txt"; then
		./genplain < "$txt" > ./phlog/"${txt##*/}".txt
	fi
done

if outofdate ./blog/index.html ./text/; then
	find ./text/ -type f ! -path '*/.*' | sort -r | ./genindex > ./blog/index.html
fi

if outofdate ./blog/feed.xml ./blog/; then
	SUFFIX=.html ./genfeed > ./blog/feed.xml
fi

if outofdate ./phlog/feed.xml ./phlog/; then
	SUFFIX=.txt ./genfeed > ./phlog/feed.xml
fi

