#!/bin/sh -e

cd "$(dirname "$0")"

if [ ! "$*" ]; then
	printf '%s\n' 'Please give a (list of) txt files to bump as arguments to this script' >&2
	exit 1
fi

for arg; do
	guidf="../guid/$arg.guid"
	if [ ! -f "$guidf" ]; then
		printf '%s\n' "No GUID file for $arg (run build script first)" >&2
		exit 1
	fi

	guid=$(cat "$guidf")
	revision=${guid##*-r}
	title=${guid%%-*}

	cat - > "$guidf" <<-EOF
		$title-r$((revision+1))
	EOF
done

./build
printf '%s\n' "$* successfully bumped" >&2

