#!/bin/sh -e

export POSIXLY_CORRECT=1

if [ ! "$*" ]; then
	printf '%s\n' 'Please give a (list of) txt files to bump as arguments to this script' >&2
	exit 1
fi

for arg; do
	arg=${arg%.txt}

	if [ ! -f "$arg.guid" ]; then
		printf '%s\n' "No GUID file for $arg (run the build script first)" >&2
		exit 1
	fi

	guid=$(cat "$arg.guid")
	revision=${guid##*-r}
	title=${guid%%-*}

	cat - > "$arg.guid" <<-EOF
		$title-r$((revision+1))
	EOF
done

./build
printf '%s\n' "$* successfully bumped" >&2

