#!/bin/sh -e

. ../blog.info/info
cat - <<-EOF
	<?xml version="1.0" encoding="UTF-8" ?>
	<rss version="2.0">
		<channel>
			<title>$TITLE</title>
			<link>$LINK/</link>
			<description>$DESCRIPTION</description>
EOF

for post in *; do
	[ -f "$post" ] || continue

	guid="../guid/$post.guid"
	if [ ! -s "$guid" ]; then
		printf '%s\n' "$post-r1" > "$guid"
	elif [ "$(wc -l < "$guid")" -gt 1 ]; then
		newguid=$(tail -n 1 < "$guid")
		cat - > "$guid" <<-EOF
			$newguid
		EOF
	fi

	cat - <<-EOF
		<item>
			<title>$(head -n 1 < "$post")</title>
			<author>$AUTHOR</author>
			<link>$LINK/$post${HTML+.html}</link>
			<guid>$(cat "$guid")</guid>
		</item>
	EOF
done

printf '%s\n' '</channel>' '</rss>'

