#!/bin/sh -e
# This script takes a txt file and generates the appropriate html file

exec < "$1"
read -r title
./htmlheader "$title"
printf '%s\n' "<h1>$title</h1>"

while IFS= read -r line; do
	case "$line" in
		'')
			if [ "$multiline" ]; then
				printf '%s\n' '</pre>'
				unset -v multiline
			fi
			;;
		.img' '*) # syntax: .img src [alt...]
			line=${line#.img }; src=${line%% *}; alt=${line#* };
			printf '%s\n' "<a href=\"$src\">" \
				"<img src=\"$src\" alt=\"$alt\">" \
				'</a>'
			;;
		.link' '*) # syntax: .link link [text shown before...]
			read -r link text <<-EOF
				${line#.link }
			EOF
			printf '%s\n' '<p>' "$text" "<a href=\"$link\">$link</a>" '</p>'
			;;
		.section' '*) # syntax: .section section
			printf '%s\n' "<h2 id=\"${line#.section }\">" "${line#.section }" '</h2>'
			;;
		.index)
			sed -n '
				1i <h2>Contents</h2><ul>
				/^\.section / {
					s/^\.section //
					s|.*|<li><a href="#&">&</a></li>|p
				}
				$a </ul>
			' < "$1"
			;;
		*'\')
			if [ "$multiline" ]; then
				printf '%s\n' "${line%'\'}"
			else
				multiline=1
				printf '%s\n' "<pre>${line%'\'}"
			fi
			;;
		*)
			if [ "$multiline" ]; then
				printf '%s\n' "$line</pre>"
			else
				printf '%s\n' "<p>$line</p>"
			fi
			unset -v multiline
			;;
	esac
done

./htmlfooter

