#!/bin/sh -e

../htmlheader "$TITLE"
printf '%s\n' '<ul>'
while read -r txt; do
	title=$(head -n 1 "$txt")
	link="${txt%.txt}.html"
	printf '%s\n' "<li><a href=\"$link\">$title</a>"
done
printf '%s\n' '</ul>'
../htmlfooter

