#!/bin/sh

cat - <<-EOF
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style>$(tr -d '\n\t' < ../blog.info/css)</style>
		<title>$1</title>
	</head>
	<body>
		$(cat ../blog.info/header)
EOF

